<a href="https://colab.research.google.com/github/RahulSuran/rahul/blob/main/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Ex1
# importing numpy 

import numpy as np 

  
# creating a 1-D list (Horizontal) 

list1 = [5, 6, 9] 

  
# creating a 1-D list (Horizontal) 

list2 = [1, 2, 3] 

  
# creating first vector 

vector1 = np.array(list1) 

  
# printing vector1 

print("First Vector          : " + str(vector1)) 

  
# creating second vector 

vector2 = np.array(list2) 

  
# printing vector2 

print("Second Vector         : " + str(vector2)) 

  
# adding both the vector 
# a + b = (a1 + b1, a2 + b2, a3 + b3) 

addition = vector1 + vector2 

  
# printing addition vector 

print("Vector Addition       : " + str(addition)) 

  
# subtracting both the vector 
# a - b = (a1 - b1, a2 - b2, a3 - b3) 

subtraction = vector1 - vector2 

  
# printing addition vector 

print("Vector Subtraction   : " + str(subtraction)) 

  
# multiplying  both the vector 
# a * b = (a1 * b1, a2 * b2, a3 * b3) 

multiplication = vector1 * vector2 

  
# printing multiplication vector 

print("Vector Multiplication : " + str(multiplication)) 

  
# dividing  both the vector 
# a / b = (a1 / b1, a2 / b2, a3 / b3) 

division = vector1 / vector2 

  
# printing division vector 

print("Vector Division       : " + str(division))
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

First Vector          : [5 6 9]
Second Vector         : [1 2 3]
Vector Addition       : [ 6  8 12]
Vector Subtraction   : [4 4 6]
Vector Multiplication : [ 5 12 27]
Vector Division       : [5. 3. 3.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [4]:
# Python Program illustrating
# numpy.random.randn() method

  

import numpy as np

  
# 2D Array   

array = np.random.randn(50, 5)

print("2D Array filled with random values : \n", array);

2D Array filled with random values : 
 [[-2.72597340e+00 -5.42521201e-01  9.43375792e-01 -1.82862851e+00
  -5.29911376e-01]
 [-9.83817402e-01 -8.64717796e-01 -7.00224902e-01  1.23743306e+00
   9.92471323e-01]
 [-1.34628041e+00 -1.24377666e+00 -1.29847990e+00 -3.09637542e-01
   9.28592790e-01]
 [ 3.16319275e-01  9.89289517e-01  1.84643688e+00 -1.37443516e+00
  -1.17877463e+00]
 [-1.44634107e+00 -3.32906025e-01  1.80656395e-02  4.78541775e-01
  -1.37818054e+00]
 [-1.01843383e+00  6.02945566e-01 -2.15287116e+00  1.13723081e+00
  -3.65365836e-01]
 [ 1.44437363e+00 -8.38204614e-01  1.03817244e+00  1.67633840e+00
  -7.88206844e-01]
 [ 9.07928005e-01 -1.89432619e-01 -1.57254035e+00 -1.05697392e-01
   3.78310597e-01]
 [-8.68744454e-01 -1.31926803e+00 -6.16390691e-01 -3.84084012e-01
  -1.00912427e-01]
 [ 1.12682220e+00 -9.57247976e-01  1.61673361e+00  1.26217029e+00
  -9.99329566e-01]
 [-4.21377792e-02 -3.35833362e-01  2.09130953e+00 -3.42712427e-01
   4.43840128e-01]
 [-7.27897249e-01  1.13229

# New Section